# Generated by Django 5.2.5 on 2025-08-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='best_seller',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
