# Generated by Django 5.2.5 on 2025-08-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='size_name',
            field=models.CharField(blank=True, choices=[('xsmall', 'X Small'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'X Large'), ('xxlarge', 'XX Large'), ('xxxlarge', 'XXX Large')], null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sizes_number',
            field=models.CharField(blank=True, choices=[('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50')], null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock_count',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='classification',
            field=models.CharField(choices=[('tshirts', 'T Shirts'), ('shorts', 'Shorts'), ('best-sellers', 'Best Seller'), ('suit', 'Suit'), ('trouser', 'Trouser')]),
        ),
    ]
