# Generated by Django 5.2.5 on 2025-08-13 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_products_in_stock_products_size_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sizes_number',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock_count',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XSmall'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XLarge'), ('XXL', 'XXLarge')], max_length=3)),
                ('stock_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsizes', to='store.products')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
